receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
service:
  pipelines:
    traces:
      exporters: ["debug"]
      processors: []
      receivers: ["otlp"]
