version: "3"

services:
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:latest@sha256:c176112df6a6aac970d54b0b2e2db950642378496c6967adc8a401179819fab0
    command:
      - run
      - /param.js
    volumes:
      - ./param.js:/param.js:ro
    depends_on:
      - otel-collector
    restart: always

  otel-collector:
    image: otel/opentelemetry-collector:latest@sha256:56951db9579bf00d3f32a4e934e19548183a86c14640798502bcd4c225976ea6
    command:
      - --config=/collector-config.yaml
    volumes:
      - ../shared/collector-config.yaml:/collector-config.yaml:ro
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "55678-55679:55678-55679"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
